import type { VisualStyle } from "../core/types";

/**
 * 内置视觉风格卡。字段只写「怎么画」，不写「画什么」。
 * suits 对应解说风格模板 id（lib/templates/builtin.ts），用于新项目推荐。
 */

type Builtin = Pick<VisualStyle, "id" | "name" | "medium" | "palette"> & Partial<VisualStyle>;

const defaults = {
  description: "",
  rendering: "",
  texture: "",
  colorGrade: "",
  saturation: "mid",
  contrast: "mid",
  lighting: "",
  atmosphere: "",
  moodTweaks: {},
  deniedMoods: [],
  lens: "",
  depthOfField: "shallow",
  composition: "",
  negative: [],
  strength: "normal",
  suits: [],
} satisfies Partial<VisualStyle>;

const list: Builtin[] = [
  {
    id: "cinematic-real",
    name: "电影写实",
    description: "真实质感的电影画面，适合历史、纪实和严肃话题",
    medium: "cinematic",
    rendering: "真实摄影质感，细节清晰，皮肤和材质自然",
    texture: "轻微胶片颗粒",
    palette: { schemes: [["#1b2530", "#3d5566", "#c9b89a"], ["#2a211b", "#6b5040", "#d8c3a5"]], accent: "#e8b04a" },
    colorGrade: "电影感调色，青橙对比，高光柔和",
    lighting: "自然主光配合轮廓光，明暗层次分明",
    atmosphere: "沉稳、真实、有叙事感",
    moodTweaks: {
      悬疑: { lighting: "低照度，大面积阴影，单一侧光源", atmosphere: "压抑、未知" },
      温暖: { lighting: "傍晚暖色逆光", colorGrade: "偏暖的金色调" },
      忧伤: { colorGrade: "低饱和的冷灰调", atmosphere: "安静、失落" },
      激昂: { lighting: "强烈的逆光和光束", atmosphere: "壮阔、有力量" },
    },
    lens: "35mm 电影镜头",
    composition: "三分构图，前后景层次",
    negative: ["卡通感", "塑料质感"],
    suits: ["serious", "documentary", "passion"],
  },
  {
    id: "noir-suspense",
    name: "暗调悬疑",
    description: "低饱和、硬光、冷色调，适合悬疑、罪案和未解之谜",
    medium: "cinematic",
    rendering: "写实，暗部细节保留",
    texture: "明显的胶片颗粒，轻微暗角",
    palette: { schemes: [["#0d1117", "#1f2a36", "#5c6f80"], ["#111014", "#2b2530", "#7a6a78"]], accent: "#c8373b" },
    colorGrade: "冷青色调，低饱和，暗部偏蓝",
    saturation: "low",
    contrast: "high",
    lighting: "硬朗的单一光源，强烈明暗对比，大面积阴影",
    atmosphere: "神秘、压抑、不安",
    moodTweaks: {
      温暖: { lighting: "冷色环境中只有一处暖色灯光", atmosphere: "短暂的安心，背景仍然暗沉" },
      轻松: { lighting: "光线稍亮，但阴影仍在", atmosphere: "表面平静，暗藏不安" },
    },
    deniedMoods: ["激昂"],
    lens: "广角略带畸变，偶尔低角度",
    composition: "大量负空间，主体偏离中心",
    negative: ["明亮的阳光", "鲜艳色彩"],
    suits: ["suspense"],
  },
  {
    id: "warm-handdrawn",
    name: "温暖手绘",
    description: "柔和的手绘插画，适合治愈、情感和生活类内容",
    medium: "illustration",
    rendering: "手绘插画，柔和的线条和色块",
    texture: "水粉纸张质感，轻微笔触",
    palette: { schemes: [["#5b3f36", "#c98a6b", "#f3dcc4"], ["#34504a", "#7ea88f", "#e7eed7"]], accent: "#f2a65a" },
    colorGrade: "温暖柔和的暖色调",
    contrast: "low",
    lighting: "柔和的漫射光，没有生硬的阴影",
    atmosphere: "温柔、治愈、安静",
    moodTweaks: {
      忧伤: { colorGrade: "偏冷的蓝灰色，保留一点暖色", atmosphere: "淡淡的惆怅" },
      悬疑: { lighting: "黄昏的昏暗光线", atmosphere: "安静中带一点好奇" },
    },
    deniedMoods: ["紧张"],
    lens: "中焦，平视",
    depthOfField: "deep",
    composition: "留白充足，画面简洁",
    negative: ["写实照片", "3D 渲染"],
    suits: ["warm", "humor"],
  },
  {
    id: "flat-infographic",
    name: "扁平信息图",
    description: "干净的扁平矢量插画，适合科普、商业和财经",
    medium: "flat-vector",
    rendering: "扁平矢量插画，几何造型，干净的色块",
    texture: "无纹理，边缘清晰",
    palette: { schemes: [["#14324a", "#2f6f9f", "#bfe0f2"], ["#1d3b33", "#2f8f76", "#c9efd9"], ["#3b2a52", "#6f56a8", "#ddd3f5"]], accent: "#ffcf3f" },
    colorGrade: "明快统一的配色",
    saturation: "high",
    lighting: "平光，无明显光源",
    atmosphere: "清晰、理性、友好",
    lens: "正视或轻微俯视的等距视角",
    depthOfField: "deep",
    composition: "主体居中，背景简洁，信息层级清楚",
    negative: ["写实照片", "复杂背景", "渐变过多"],
    strength: "strong",
    suits: ["science", "serious"],
  },
  {
    id: "anime",
    name: "日系动漫",
    description: "日系动画电影质感，适合故事演绎和青春题材",
    medium: "anime",
    rendering: "日系动画电影风格，精致的背景美术，干净的人物线条",
    texture: "赛璐璐上色",
    palette: { schemes: [["#1c2b4a", "#4f7cc4", "#cfe3ff"], ["#4a2338", "#c65b86", "#ffd9e6"]], accent: "#ffd166" },
    colorGrade: "通透明亮，天空湛蓝",
    saturation: "high",
    lighting: "明亮的自然光，丁达尔光束",
    atmosphere: "青春、清新、有情绪张力",
    moodTweaks: {
      忧伤: { lighting: "雨天或黄昏", colorGrade: "偏冷的蓝紫色" },
      悬疑: { lighting: "夜晚，霓虹或路灯", atmosphere: "神秘" },
      激昂: { lighting: "逆光和速度线般的光效", atmosphere: "热血" },
    },
    lens: "中焦，动画分镜式构图",
    composition: "人物与大面积天空或场景",
    negative: ["写实照片", "3D 渲染"],
    suits: ["humor", "passion", "warm"],
  },
  {
    id: "ink-guofeng",
    name: "国风水墨",
    description: "水墨写意，适合历史、传统文化和古诗词",
    medium: "ink",
    rendering: "中国水墨画，写意笔法，墨色浓淡变化",
    texture: "宣纸纹理，墨迹晕染",
    palette: { schemes: [["#1e1e1c", "#5a5a52", "#e9e4d6"], ["#2b1d17", "#8c3b2a", "#efe6d2"]], accent: "#b8322a" },
    colorGrade: "黑白灰为主，点缀朱红或石青",
    saturation: "low",
    lighting: "无明确光源，靠墨色浓淡表现明暗",
    atmosphere: "空灵、悠远、含蓄",
    deniedMoods: ["科技"],
    lens: "散点透视",
    depthOfField: "deep",
    composition: "大量留白，主体偏于一角",
    negative: ["写实照片", "现代建筑", "鲜艳饱和色"],
    strength: "strong",
    suits: ["documentary", "serious"],
  },
  {
    id: "clay-3d",
    name: "3D 黏土",
    description: "圆润可爱的黏土 3D，适合幽默和轻松科普",
    medium: "3d",
    rendering: "黏土定格动画风格的 3D 模型，圆润造型",
    texture: "黏土表面的指纹和细微凹凸",
    palette: { schemes: [["#3a2f5b", "#7b6ccf", "#e3ddff"], ["#5b3a2a", "#e0874f", "#ffe3cc"]], accent: "#ffb703" },
    colorGrade: "明亮糖果色",
    saturation: "high",
    contrast: "low",
    lighting: "柔和的棚拍灯光，轻微投影",
    atmosphere: "可爱、轻松、有趣",
    deniedMoods: ["悬疑", "忧伤"],
    lens: "微距，轻微俯视",
    composition: "主体居中，背景简单",
    negative: ["写实照片", "恐怖元素"],
    suits: ["humor", "science", "roast"],
  },
  {
    id: "cyber-neon",
    name: "赛博霓虹",
    description: "霓虹光影的未来都市，适合科技和未来话题",
    medium: "cinematic",
    rendering: "写实的未来科技场景，反光材质",
    texture: "潮湿的反光地面，空气中的薄雾",
    palette: { schemes: [["#0b0620", "#3a1f7a", "#35d0ff"], ["#10061a", "#7a1f6a", "#ff5fd2"]], accent: "#35f2ff" },
    colorGrade: "品红与青色霓虹对比",
    saturation: "high",
    contrast: "high",
    lighting: "霓虹灯和屏幕光作为主光源，边缘光强烈",
    atmosphere: "未来、科技、疏离",
    moodTweaks: {
      温暖: { colorGrade: "加入暖橙色灯光", atmosphere: "冷色城市里的一点温度" },
    },
    lens: "广角，低角度仰拍",
    composition: "强透视纵深，线条引导",
    negative: ["田园风光", "自然阳光"],
    suits: ["science", "passion"],
  },
  {
    id: "retro-film",
    name: "复古胶片",
    description: "老照片与胶片质感，适合怀旧和年代故事",
    medium: "photo",
    rendering: "胶片摄影，自然的光学瑕疵",
    texture: "明显的胶片颗粒，轻微漏光和褪色",
    palette: { schemes: [["#3a2e22", "#8a6f4e", "#e8d9b8"], ["#2e3a33", "#6f8a6a", "#e2e6c8"]], accent: "#d9822b" },
    colorGrade: "褪色的暖黄调，暗部偏绿",
    saturation: "low",
    lighting: "自然光，略微过曝的高光",
    atmosphere: "怀旧、温情、时光流逝",
    lens: "50mm 定焦",
    composition: "生活化的抓拍构图",
    negative: ["数码锐利感", "现代电子产品"],
    suits: ["warm", "documentary"],
  },
  {
    id: "comic-pop",
    name: "漫画分镜",
    description: "粗线条的美式漫画，适合吐槽和搞笑",
    medium: "comic",
    rendering: "美式漫画，粗黑描边，夸张的表情和动作",
    texture: "网点纸和半调网纹",
    palette: { schemes: [["#1f1f3a", "#e63946", "#f1faee"], ["#1d3557", "#457b9d", "#f1faee"]], accent: "#ffd60a" },
    colorGrade: "高饱和的平涂色块",
    saturation: "high",
    contrast: "high",
    lighting: "戏剧化的平涂阴影",
    atmosphere: "夸张、幽默、有冲击力",
    deniedMoods: ["忧伤"],
    lens: "夸张的透视和特写",
    depthOfField: "deep",
    composition: "动态斜构图",
    negative: ["写实照片", "柔和渐变"],
    suits: ["roast", "humor"],
  },
];

export const builtinVisualStyles: VisualStyle[] = list.map((s) => ({ ...defaults, ...s, builtin: true }) as VisualStyle);

/** 按解说风格推荐画面风格：先列出适合的，其余保持原顺序 */
export function recommendVisualStyles<T extends Pick<VisualStyle, "suits">>(templateId: string, styles: T[]): T[] {
  return [...styles.filter((s) => s.suits.includes(templateId)), ...styles.filter((s) => !s.suits.includes(templateId))];
}
